---
#Authorize to the cluster and register a cookie to be used for future API calls
- name: Set fact for basic authorization string
  set_fact:
    auth_string: "{{ prism_user }}:{{ prism_password }}"

- name: Debug | Print Basic authorization string
  debug:
    var: auth_string
  when: global_debug

- name: Set fact for authorization header
  set_fact:
    encoded_credentials: "Basic {{ auth_string | b64encode(encoding='ascii') }}"

- name: Debug | Print authorization header
  debug:
    var: encoded_credentials
  when: global_debug

- name: Auth to the cluster
  uri:
    url: "{{ prism_api_v3 }}/users/me"
    method: GET
    validate_certs: "{{ validate_certs }}"
    body_format: json
    headers:
      Authorization: "{{ encoded_credentials }}"
    status_code: 200
    return_content: yes
  register: login
  ignore_errors: no

- name: Set fact session_cookie
  set_fact:
    session_cookie: "{{ login.set_cookie }}"

- name: Debug | Print session_cookie
  debug:
    var: session_cookie
  when: global_debug